ALTER TABLE "Announcement" ADD COLUMN "category" TEXT NOT NULL DEFAULT 'GENERAL';
ALTER TABLE "Announcement" ADD COLUMN "priority" TEXT NOT NULL DEFAULT 'NORMAL';
ALTER TABLE "Announcement" ADD COLUMN "audience" TEXT NOT NULL DEFAULT 'EVERYONE';
ALTER TABLE "Announcement" ADD COLUMN "publishAt" TIMESTAMP(3);
ALTER TABLE "Announcement" ADD COLUMN "expiresAt" TIMESTAMP(3);